### PR TITLE
fix: hashtag regex compile failure on php 7.3

### PR DESCRIPTION
**Pull request by TheNewSound**
Please accept pull-request and release new version in packagist

### CODE REVIEW

**Comment by atymic** [comment]
Hey @TheNewSound 

Can you add some information on why this change is needed?
Thanks

**Comment by TheNewSound** [comment]
> Hey @TheNewSound
> 
> Can you add some information on why this change is needed?
> Thanks

[PHP 7.3 - preg_replace(): Compilation failed: invalid range in character class at offset 24](https://github.com/thujohn/twitter/issues/250)

**Comment by atymic** [comment]
Thanks. Will merge and tag new release now.

**Comment by atymic** [comment]
Tagged: https://github.com/atymic/laravel-twitter/releases/tag/2.2.7

**Pull request merged**
